"""Generate the earthdata stac spec. Indended to be run as, e.g. a pre-commit hook or CI step."""

import json
import os

import requests


def main() -> None:
    """Generate the earthdata stac spec."""
    with requests.get("https://cmr.earthdata.nasa.gov/stac") as r:
        r.raise_for_status()
        res = json.loads(r.text)
    mapping = {}

    templ = (
        '"""This file is auto-generated by gen-earthdata-stac-spec.py. '
        + 'Do not edit directly."""\n\n'
    )
    for link in res["links"]:
        key = link["title"].replace(" ", "_").upper()
        if key == "CMR-STAC_DOCUMENTATION":
            continue
        mapping[key] = link["href"]
    alpha_list = list(mapping.keys())
    alpha_list.sort()
    entries = []
    for pvdr_id in alpha_list:
        entries += [f'    "{pvdr_id}": "{mapping[pvdr_id]}"']
    dict_str = "EARTHDATA_PROVIDERS = {\n" + ",\n".join(entries) + ",\n}\n"

    templ += dict_str
    file_path = os.path.realpath(os.path.dirname(__file__))
    outfile = os.path.join(
        file_path, "..", "multiearth", "provider", "earthdata_providers.py"
    )
    with open(outfile, "w") as f:
        f.write(templ)


if __name__ == "__main__":
    main()
    exit(0)
